export const NUEVO_EMPLEADO = "NUEVO_EMPLEADO"
export const NUEVO_EMPLEADO_EXITO = "NUEVO_EMPLEADO_EXITO"
export const NUEVO_EMPLEADO_ERROR = "NUEVO_EMPLEADO_ERROR"

export const VER_EMPLEADOS = "MOSTRAR_EMPLEADOS"
export const VER_EMPLEADOS_EXITO = "MOSTRAR_EMPLEADOS_EXITO"
export const VER_EMPLEADOS_ERROR = "MOSTRAR_EMPLEADOS_ERROR"